name: "build-test"
on: 
  pull_request:
    # branches: 
    #   - master
  # push:
    # branches:
    #   - master

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:

    - uses: actions/checkout@v2
      with: 
        submodules: 'false'

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: Setup Ruby tools
      run: |
        bundle config path vendor/bundle
        bundle install
    
    - name: Run Tests 
      run: bundle exec fastlane ci_pr

    - uses: MeilCli/danger-action@v5.0.0
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.MOBILE_CI_GITHUB_API_TOKEN }}

